[package]
name = "git-green"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
chrono = { version = "0.4", features = ["clock"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
assert_matches = "1"
